### PR TITLE
python 3.8, unpin packages, use mamba

### LINKED ISSUE #118: bump to Python 3.8
All images currently pin `python=3.7`. Just wanted to open this issue in case anyone is wanting to bump to 3.8. The walrus operator seems pretty fun https://docs.python.org/3/whatsnew/3.8.html ...

### PR DESCRIPTION
**Pull request by scottyhq**
i was experimenting with rebuilding images locally with new conda-lock, python3.8 (since 3.9 is now out) and mamba, and it is speedy and seems to work well.

replaces #137, closes #118

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Any thoughts on how to handle the 3.8 rollout to the jupyterhubs? Short of making things configurable (through KubeSpawner) I don't see a great option.

**Comment by scottyhq** [comment]
> Any thoughts on how to handle the 3.8 rollout to the jupyterhubs? Short of making things configurable (through KubeSpawner) I don't see a great option. 

Do you fore any major issues @TomAugspurger ? I'm tempted to just go for it. 

Although, I was thinking now that pangeo-bot is integrated I think a neat testing feature would be to push image builds in a PR to DockerHub and automatically add binder buttons for testing https://mybinder.readthedocs.io/en/latest/howto/gh-actions-badges.html#example-1-comment-on-pull-request-with-a-binder-badge

**Comment by scottyhq** [comment]
/condalock 

(forgot to commit new conda-lock environment file initially)

**Comment by TomAugspurger** [comment]
> Do you foresee any major issues @TomAugspurger ? I'm tempted to just go for it.

Nothing in particular. We could ping people to try out their workflows on staging before deploying to prod.

**Comment by scottyhq** [comment]
FWIW, adding mamba definitely speeds up conda-lock, our 3 environments now solve in [2min](https://github.com/pangeo-data/pangeo-docker-images/actions/runs/305151891) rather than [9.5 min](https://github.com/pangeo-data/pangeo-docker-images/actions/runs/305079834), and this should also improve binder build speeds for environments with lots of packages.

**Comment by scottyhq** [comment]
ping @jhamman @rabernat @rsignell-usgs , going to merge this, if you want to test things out with the master tag (pangeo/pangeo-notebook:master)

**Pull request merged**
