### PR TITLE
Add pycamhd

### PR DESCRIPTION
**Pull request by tjcrone**

### CODE REVIEW

**Comment by tjcrone** [comment]
Looks like someone who controls the pangeo-bot needs to accept my invitation for write access to my fork. @rabernat can you accept my invitation?

**Comment by tjcrone** [comment]
https://github.com/ooicloud/pangeo-docker-images/invitations

**Comment by scottyhq** [comment]
Hi @tjcrone  I'm wondering if the CI isn't workoing because of an organization setting you have for ooicloud? 

For example, here is a successful PR workflow https://github.com/pangeo-data/pangeo-docker-images/pull/122  that ran on a fork (but on a personal account), and a link to the log showing pangeo-bot adding a commit.
https://github.com/pangeo-data/pangeo-docker-images/runs/1054291204?check_suite_focus=true 

it would be good to know the setting that is blocking and document it.

As a workaround, if *you* add `/condalock` in the first line of a comment the CI should run

**Comment by tjcrone** [comment]
@scottyhq, what I see in the logs is that the pangeo-bot is trying to push a commit to my fork, and it doesn't have permissions. I added pangeo-bot as a collaborator, but the invitation needs to be accepted. Is this not the issue?

**Comment by tjcrone** [comment]
Okay condalock running. We'll see what happens. I see that pangeo-bot definitely was able to push commits to https://github.com/shunzlu/pangeo-docker-images, and because pangeo-bot has not accepted my invitation to be a contributor, I don't think it can push commits to my fork. Is there a way that I can allow pangeo-bot to push to my fork without it accepting my invitation to collaborate?

**Comment by tjcrone** [comment]
Another interesting thing when I check on the current running actions, is that the condalock I just fired in the comment above appears to be associated with #122, not this PR. Unexpected but hopefully not an issue.

**Comment by tjcrone** [comment]
I see this which I think is what you would expect if the fork was private. But it is not private:
```
remote: Permission to ooicloud/pangeo-docker-images.git denied to pangeo-bot.
fatal: unable to access 'https://github.com/ooicloud/pangeo-docker-images/': The requested URL returned error: 403
##[error]Process completed with exit code 128.
```

**Comment by scottyhq** [comment]
/condalock

> pangeo-bot has not accepted my invitation to be a contributor, I don't think it can push commits to my fork. Is there a way that I can allow pangeo-bot to push to my fork without it accepting my invitation to collaborate? 

This what I was asking about. I'm not sure if there is some sort of github organization setting that is different from forks on personal accounts?? In any case, I just logged in as pangeo-bot and accepted your organization invite, let's see if it works now.

> Another interesting thing when I check on the current running actions, is that the condalock I just fired in the comment above appears to be associated with #122

Looks like I accidentally left in this block when testing out some new github actions options. I'll fix it in a separate PR
https://github.com/pangeo-data/pangeo-docker-images/blob/37962231c78b7cc796c02a52b20aef3f8acf110b/.github/workflows/Test.yml#L7-L11

**Review by scottyhq — APPROVED** [review]

**Comment by tjcrone** [comment]
Well that worked like a dream @scottyhq. Sorry I was unable to find the setting. I looked and didn't find anything promising. I take it that pangeo-bot has been able to push to other forks without being a collaborator?

Okay for me to merge? Thanks!

**Pull request merged**
