### PR TITLE
Add IBM's JupyterLab s3 Browser

### LINKED ISSUE #310: Enable s3 browser labextension in pangeo-notebook image
@yuvipanda and I recently discovered [jupyterlab-s3-browser](https://github.com/IBM/jupyterlab-s3-browser) and decided it would make a lot of sense to have this in our cloud hubs. It will enable users to more easily take advantage of object storage by providing a convenient UI for browsing it.

This is also related to https://github.com/2i2c-org/docs/pull/138, as it will improve the whole UX around object storage for 2i2c Pangeo hubs.

### PR DESCRIPTION
**Pull request by yuvipanda**
Installs https://github.com/IBM/jupyterlab-s3-browser, which
can be used to look at S3 via a graphical interface.

closes #310

### CODE REVIEW

**Comment by scottyhq** [comment]
While the build succeeds the package version changes coming from pip are a bit worrying, so this is another case where ideally this could come from conda-forge: 

(excerpt below from 'Build Image' log) https://github.com/pangeo-data/pangeo-docker-images/runs/6142797226?check_suite_focus=true
```
2022-04-23T22:16:52.9738422Z Installing collected packages: python-dateutil, jmespath, botocore, s3transfer, fsspec, aiobotocore, singleton-decorator, s3fs, boto3, jupyterlab-s3-browser, gh-scoped-creds
2022-04-23T22:16:52.9739019Z   Attempting uninstall: python-dateutil
2022-04-23T22:16:52.9750474Z     Found existing installation: python-dateutil 2.7.5
2022-04-23T22:16:52.9811600Z     Uninstalling python-dateutil-2.7.5:
2022-04-23T22:16:52.9820691Z       Successfully uninstalled python-dateutil-2.7.5
2022-04-23T22:16:53.0341222Z   Attempting uninstall: jmespath
2022-04-23T22:16:53.0353693Z     Found existing installation: jmespath 1.0.0
2022-04-23T22:16:53.0396420Z     Uninstalling jmespath-1.0.0:
2022-04-23T22:16:53.0454002Z       Successfully uninstalled jmespath-1.0.0
2022-04-23T22:16:53.0655785Z   Attempting uninstall: botocore
2022-04-23T22:16:53.0669263Z     Found existing installation: botocore 1.24.21
2022-04-23T22:16:53.1587577Z     Uninstalling botocore-1.24.21:
2022-04-23T22:16:53.1782775Z       Successfully uninstalled botocore-1.24.21
2022-04-23T22:16:53.8261366Z   Attempting uninstall: s3transfer
2022-04-23T22:16:53.8273993Z     Found existing installation: s3transfer 0.5.2
2022-04-23T22:16:53.8340673Z     Uninstalling s3transfer-0.5.2:
2022-04-23T22:16:53.8347668Z       Successfully uninstalled s3transfer-0.5.2
2022-04-23T22:16:53.8756710Z   Attempting uninstall: fsspec
2022-04-23T22:16:53.8769297Z     Found existing installation: fsspec 2022.3.0
2022-04-23T22:16:53.8910481Z     Uninstalling fsspec-2022.3.0:
2022-04-23T22:16:53.8918690Z       Successfully uninstalled fsspec-2022.3.0
2022-04-23T22:16:53.9737879Z   Attempting uninstall: aiobotocore
2022-04-23T22:16:53.9748927Z     Found existing installation: aiobotocore 2.2.0
2022-04-23T22:16:53.9827240Z     Uninstalling aiobotocore-2.2.0:
2022-04-23T22:16:53.9833763Z       Successfully uninstalled aiobotocore-2.2.0
2022-04-23T22:16:54.0191159Z   Attempting uninstall: s3fs
2022-04-23T22:16:54.0202898Z     Found existing installation: s3fs 2022.3.0
2022-04-23T22:16:54.0235665Z     Uninstalling s3fs-2022.3.0:
2022-04-23T22:16:54.0241748Z       Successfully uninstalled s3fs-2022.3.0
2022-04-23T22:16:54.0447831Z   Attempting uninstall: boto3
2022-04-23T22:16:54.0459909Z     Found existing installation: boto3 1.21.21
2022-04-23T22:16:54.0602492Z     Uninstalling boto3-1.21.21:
2022-04-23T22:16:54.0618084Z       Successfully uninstalled boto3-1.21.21
2022-04-23T22:16:54.2134091Z Successfully installed aiobotocore-1.4.2 boto3-1.17.106 botocore-1.20.106 fsspec-2021.10.1 gh-scoped-creds-4.1 jmespath-0.10.0 jupyterlab-s3-browser-0.11.1 python-dateutil-2.8.2 s3fs-2021.10.1 s3transfer-0.4.2 singleton-decorator-1.0.0
2022-04-23T22:16:54.2142879Z [91mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
2022-04-23T22:16:54.2143643Z sat-stac 0.4.1 requires python-dateutil~=2.7.5, but you have python-dateutil 2.8.2 which is incompatible.
2022-04-23T22:16:54.2144267Z intake-esm 2021.8.17 requires h5netcdf>=0.8.1, but you have h5netcdf 0.0.0 which is incompatible.
2022-04-23T22:16:54.2144711Z gcsfs 2022.3.0 requires fsspec==2022.3.0, but you have fsspec 2021.10.1 which is incompatible.
2022-04-23T22:16:54.2145589Z earthdata 0.2.2 requires python-benedict<0.26,>=0.25, but you have python-benedict 0.24.3 which is incompatible.
2022-04-23T22:16:54.2146066Z earthdata 0.2.2 requires s3fs<2023,>=2021.11, but you have s3fs 2021.10.1 which is incompatible.
2022-04-23T22:16:54.2146480Z awscli 1.22.76 requires botocore==1.24.21, but you have botocore 1.20.106 which is incompatible.
2022-04-23T22:16:54.2146921Z awscli 1.22.76 requires s3transfer<0.6.0,>=0.5.0, but you have s3transfer 0.4.2 which is incompatible.
```

**Comment by rabernat** [comment]
@yuvipanda - is the conda package working yet? Can we try this again with conda?

**Comment by yuvipanda** [comment]
@rabernat i didn't make a conda package for this - only for gh-scoped-creds.

**Comment by yuvipanda** [comment]
switching to conda won't change this because they pin s3fs here - https://github.com/IBM/jupyterlab-s3-browser/blob/2604cf09818c0bc15d980038e38fc22f2320adfc/setup.py#L97. We should try to get them to loosen it, that'll fix it both for pip and conda.

**Comment by rabernat** [comment]
jupyterlab-s3-browser 0.12 (just released) has unpinned the s3fs dependency 🚀

**Pull request merged**
