### PR TITLE
add eofs package

### PR DESCRIPTION
**Pull request by rabernat**
This is a very useful generic package for EOF analysis.

### CODE REVIEW

**Comment by scottyhq** [comment]
/condalock

note to improve CI and auto-request additional reviewers: https://github.com/pangeo-data/pangeo-docker-images/issues/92

**Comment by scottyhq** [comment]
Hmm.. conflicts occur because https://github.com/pangeo-data/pangeo-docker-images/pull/97 was just merged adding a few packages that this PR doesn't have. So before locking the environment we need to ensure that any environment.yml is rebased to match environment.yml on `master` branch...

**Comment by scottyhq** [comment]
@rabernat - I'm not sure what happened here, seems like your fork got out of sync. I think the easiest solution is to 1) close this PR, 2) make sure your fork is in sync with upstream master, 3) new branch and PR adding EOFS

**Comment by rabernat** [comment]
> I'm not sure what happened here, seems like your fork got out of sync.

I'm not sure I understand. In my original commit (f5cba60f1dd9efbd938710e649dcf93f2e26f811), I only changed one line. I started from an update master. 

I added this in #100.

**Pull request closed without merging**
