### PR TITLE
Add jupyterlab-nvdashboard

### LINKED ISSUE #321: Add jupyterlab-nvdashboard to ml images
It would be great to have this enabled in our GPU hubs

https://github.com/rapidsai/jupyterlab-nvdashboard

https://developer.nvidia.com/blog/gpu-dashboards-in-jupyter-lab/

### PR DESCRIPTION
**Pull request by weiji14**
A JupyterLab extension for displaying dashboards of GPU usage. Repo at https://github.com/rapidsai/jupyterlab-nvdashboard

Only adding this to `pytorch-notebook` and `ml-notebook`.

Closes #321

### CODE REVIEW

**Comment by weiji14** [comment]
Locking the `forge` environment takes >20minutes and times out for some reason (ml-notebook only takes <2min). Might need to look into this separately.

**Comment by weiji14** [comment]
> Locking the `forge` environment takes >20minutes and times out for some reason (ml-notebook only takes <2min). Might need to look into this separately.

Only takes 6min now at https://github.com/pangeo-data/pangeo-docker-images/actions/runs/4999316441/jobs/8955588572#step:4:19. Not sure what happened, but ready for review!

**Review by scottyhq — APPROVED** [review]

**Comment by weiji14** [comment]
Thanks @scottyhq!

**Pull request merged**
