### PR TITLE
Add lonboard package

### PR DESCRIPTION
**Pull request by scottyhq**
testing alternative to #522 ...

### CODE REVIEW

**Comment by scottyhq** [comment]
trouble locking ml-notebook: 
```
│  └─ lonboard [0.6.0|0.7.0|0.7.0b2|0.7.1] would require
│     └─ pyarrow >=14.0.1 , which can be installed (as previously explained);
└─ tensorflow >=2.14.0 *cuda118* is not installable because it requires
   └─ tensorflow-base [2.14.0 cuda118py310h2e5981e_0|2.14.0 cuda118py311h0476658_0|2.14.0 cuda118py39hbe86951_0], which requires
      ├─ libabseil >=20230125.3,<20230126.0a0 , which conflicts with any installable versions previously reported;
      └─ libgrpc >=1.54.3,<1.55.0a0 , which conflicts with any installable versions previously reported.
```

**Comment by weiji14** [comment]
> trouble locking ml-notebook:
> 
> ```
> │  └─ lonboard [0.6.0|0.7.0|0.7.0b2|0.7.1] would require
> │     └─ pyarrow >=14.0.1 , which can be installed (as previously explained);
> └─ tensorflow >=2.14.0 *cuda118* is not installable because it requires
>    └─ tensorflow-base [2.14.0 cuda118py310h2e5981e_0|2.14.0 cuda118py311h0476658_0|2.14.0 cuda118py39hbe86951_0], which requires
>       ├─ libabseil >=20230125.3,<20230126.0a0 , which conflicts with any installable versions previously reported;
>       └─ libgrpc >=1.54.3,<1.55.0a0 , which conflicts with any installable versions previously reported.
> ```

Yeah, the `libgrpc` conflicts looks like a similar issue to https://github.com/pangeo-data/pangeo-docker-images/issues/489, which will be resolved once we can merge https://github.com/pangeo-data/pangeo-docker-images/pull/514 (need to figure out how to make `conda-lock` happy).

**Review by weiji14 — APPROVED** [review]
Thanks @scottyhq, we can close #522 afterwards. I've been meaning to test `lonboard` on binder, but struggling because it doesn't have a lot of RAM. Will just hope that the lonboard <-> anywidget compatibility works :crossed_fingers:

**Pull request merged**
