### PR TITLE
Add nbstripout and python-gist to pangeo-notebook env

### PR DESCRIPTION
**Pull request by rsignell-usgs**
/condalock

python-gist is what I use for creating gists from JupyterLab
nbstripout for stripping output from notebooks prior to git commit

### CODE REVIEW

**Comment by scottyhq** [comment]
\conda-lock

Thanks @rsignell-usgs , as it currently stands you have to be a member of `pangeo-data@pangeo-admin` team for the `\condalock` command to have any effect

**Comment by scottyhq** [comment]
\condalock

**Comment by rsignell-usgs** [comment]
@scottyhq, what happens now?     
Looks like someone is supposed to review before we merge?

**Comment by scottyhq** [comment]
> Looks like someone is supposed to review before we merge? 

Yes. Mainly to ensure `/condalock` gets run. We need to revamp CI a bit to automate this (https://github.com/pangeo-data/pangeo-docker-images/issues/92)

**Pull request merged**
