### PR TITLE
Add parcels package

### PR DESCRIPTION
**Pull request by jbusecke**
[Ocean Parcels](https://oceanparcels.org) is an awesome tool to run lagrangian particles. It used to be on the notebook image for ocean.pangeo.io and due to the heavy list of dependencies, it is cumbersome to install on the fly.

Could we add this to the standard notebook image?

### CODE REVIEW

**Comment by scottyhq** [comment]
thanks @jbusecke , fine by me, but we have to tackle https://github.com/pangeo-data/pangeo-cloud-federation/issues/859 before this new environment can be used in the hub by default.

also, just a note that the pangeo-notebook image is now 3.4GB... would be great to revisit ways to make this slimmer to speed up start times https://github.com/pangeo-data/pangeo-docker-images/pull/162/checks?check_run_id=1398080473

**Comment by jbusecke** [comment]
> also, just a note that the pangeo-notebook image is now 3.4GB... 

Is this due to this addition? Or has it grown in general? If its the former, I am very unsure how we could slim this down. Part of my motivation to add this particular package to the main notebook is that I am having trouble manually installing all the dependencies (see [here](https://github.com/pangeo-data/pangeo/pull/792)).

**Comment by scottyhq** [comment]
it's hard to tell exactly, because this addition also updates existing packages, but the size bump with this PR is ~400MB comparing to current master image:
```
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
pangeo/pangeo-notebook   master              fd5c23c0d0e5        3 days ago          3.04GB
```
@jbusecke don't worry about addressing the size in this PR, I was just wanted to flag and we can continue the size and packages discussion here https://github.com/pangeo-data/pangeo-docker-images/issues/28

**Comment by jbusecke** [comment]
Thanks for the follow up. So this one is currently on hold until upstream issues are fixed? Is there anything else I can do to help at this point?

**Comment by scottyhq** [comment]
Yes @jbusecke , this is currently on hold, but it seems like you can use the workaround detailed here for now https://github.com/pangeo-data/pangeo/pull/792#issuecomment-727132517

**Review by scottyhq — APPROVED** [review]

**Comment by jbusecke** [comment]
I noticed that parcels is still not available on the production env. Is this still held up by the above? Or did something go wrong?

**Comment by scottyhq** [comment]
@jbusecke as of https://github.com/pangeo-data/pangeo-cloud-federation/pull/897 parcels is now on the staging hubs:

```
(notebook) jovyan@jupyter-scottyhq:~$ conda list | grep parcels
parcels                   2.2.1            py38h32f6830_0    conda-forge
```

**Comment by jbusecke** [comment]
Thanks a lot for the headsup @scottyhq

**Pull request merged**
