### PR TITLE
bump miniforge and upgrade packages

### PR DESCRIPTION
**Pull request by scottyhq**
/condalock

this should pull in some new packages like xarray=0.17

### CODE REVIEW

**Comment by scottyhq** [comment]
/condalock

apparently slash command can't be in first PR comment.

**Comment by scottyhq** [comment]
want to ensure we get rioxarray 0.3.1 for compatibility with xarray 0.17 https://github.com/corteva/rioxarray/issues/254

also i think @jbednar was recommending pinning bokeh=2.2 for a while?

**Comment by jbednar** [comment]
Bokeh 2.3 compatible versions of Panel and HoloViews are being released today, so it should be fine not to pin now.

**Comment by scottyhq** [comment]
closing in favor of #191

**Pull request closed without merging**
