### PR TITLE
Add jax notebook

### PR DESCRIPTION
**Pull request by rabernat**
This is not working for me locally, but it's a start.

cc @dhruvbalwada

### CODE REVIEW

**Comment by scottyhq** [comment]
Similar to the discussion with the new pytorch image: Do people use jax and tensorflow together, or is it typically one or the other? In an ideal world these libraries (tensorflow, pytorch, jax, cupy) could all have compatible dependencies, and not be giant, so we could have a single environment... but that does not seem to be the case currently (#302). In any case, if adding a separate jax notebook, do we remove jax from the tensoflow image:

https://github.com/pangeo-data/pangeo-docker-images/blob/e56a5fea09fb52362f53ed0f82735673c97b88e3/ml-notebook/environment.yml#L8-L10

**Comment by ngam** [comment]
https://anaconda.org/ngam/jaxlib/files

I uploaded jaxlib with cuda for py37, py38, p39, and py310 here. I am fairly certain the actual product is okay, but we may need to fine tune the build process a little more.

`conda create -n jax39 python=3.9 jaxlib==*=*cuda* jax -c ngam -c conda-forge`. Note this is only cuda112 (11.2+).

**Comment by ngam** [comment]
> Similar to the discussion with the new pytorch image: Do people use jax and tensorflow together, or is it typically one or the other?

I would advocate for coupling jax and tensorflow. Jax, in many ways, is an offshoot of tensorflow (if you look at the build logs, they're largely similar; jax borrows from tensorflow)

**Comment by ngam** [comment]
> In an ideal world these libraries (tensorflow, pytorch, jax, cupy) could all have compatible dependencies, and not be giant, so we could have a single environment... but that does not seem to be the case currently (#302). In any case, if adding a separate jax notebook, do we remove jax from the tensoflow image?:

fwiw, you should be able to get that sorted. The problem here isn't in these libraries per se, it is in the many other deps we have. Here's how I would approach it: Start with these four and then add others to see where things break. For example, while torch and tensorflow could easily coexist, adding torchgeo breaks that --- why? Because in conda-forge, tensorflow is now iwth icu 70.1 but torchgeo is with gdal which is stuck at icu <70.1. But that will at some point get fixed. 

When I was working on the other containers based on NGC, I notice problems start popping up with random packages that I am not sure if they are useful to anyone --- or rather, I have never heard about them, so I have no idea what to make of them. A question is then, if some small package breaking down all compatibility, is it worth having? Who's using it and why? Could we replace it with something else? Unfortunately, I cannot make these calls because I am relatively new to the whole ecosystem, but I am sure people here will be able to figure it out.

**Comment by ngam** [comment]
I wanna add, fixing these discrepancies and conflicts is often a simple PR away or a simple nudge to the feedstock maintainers, so it is not like reinventing the whole thing, just a bit of nudging...

**Comment by ngam** [comment]
gdal icu70 PR: https://github.com/conda-forge/gdal-feedstock/pull/632 so hopefully things should be smoother soon-ish

**Comment by ngam** [comment]
chased the gdal issue... now rasterio... after that xlayers... it's an endless game with these geo pkgs 😰

**Comment by rabernat** [comment]
We can definitely drop xlayers! But not rasterio.

**Pull request closed without merging**
