### PR TITLE
Test that apache_beam is installed in the forge image

### PR DESCRIPTION
**Pull request by yuvipanda**
conda-lock doesn't actually install any pip packages I
believe.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Something super funky is going on here.

```
$ mamba install -c conda-forge apache-beam-with-gcp
$ mamba list | grep beam
apache-beam               2.40.0           py39hb9d737c_0    conda-forge
apache-beam-with-gcp      2.40.0           py39hf3d152e_0    conda-forge
$ python3
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import apache_beam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'apache_beam'
>>> 
```

**Comment by yuvipanda** [comment]
As expected, https://github.com/pangeo-data/pangeo-docker-images/runs/7547348518?check_suite_focus=true fails - https://github.com/conda-forge/apache-beam-feedstock/pull/52 should fix it!

**Comment by yuvipanda** [comment]
https://github.com/pangeo-data/pangeo-docker-images/pull/362/commits/2542609d25955c3f371485da71a29a77246fa610 made it pass, yay! So I think https://github.com/conda-forge/apache-beam-feedstock/pull/52 will definitely fix it I think.

**Comment by scottyhq** [comment]
> conda-lock doesn't actually install any pip packages I believe.

In theory after v1.0 it does https://conda-incubator.github.io/conda-lock/pip/ ! But support for all the pip syntax isn't fully supported. This appears to work though: 

*Use new `conda-lock.yml` format to deal with both conda and pip packages:*
```
conda-lock lock -p linux-64
conda-lock install -n test
# Note also you can render conda-compatible lockfiles `conda-lock render -k env`, but there is a warning about how these don't necessarily preserve identical environments
```

I think it could be worth supporting `conda-lock.yml` files here:
https://github.com/pangeo-data/pangeo-docker-images/blob/3d0d6eeae9e6ded756bc5f6137aace43151524c8/base-image/Dockerfile#L156
see also #306  

But also it's great to fix the conda-forge version not mix with pip, so thanks for doing that!

**Review by scottyhq — APPROVED** [review]

**Comment by yuvipanda** [comment]
Thanks a lot, @scottyhq! I removed the explicit dependency as my conda-forge PR was merged, and the tests pass now! \o/

**Comment by yuvipanda** [comment]
Agree that switching to the yaml format is probably better!

**Pull request merged**
