### PR TITLE
Switch to using conda-forge for gh-scoped-creds

### PR DESCRIPTION
**Pull request by yuvipanda**
Follow-up https://github.com/pangeo-data/pangeo-docker-images/pull/305

### CODE REVIEW

**Comment by rabernat** [comment]
The slash command is failing - https://github.com/pangeo-data/pangeo-docker-images/runs/6120619587?check_suite_focus=true

```
Encountered problems while solving:
  - nothing provides requested gh-scoped-creds
```

Are you sure the conda-forge package is published?

**Comment by yuvipanda** [comment]
Trying again, I think it's there now?

**Comment by yuvipanda** [comment]
Works now!

**Review by scottyhq — APPROVED** [review]

**Pull request merged**
