### PR TITLE
add-argopy

### PR DESCRIPTION
**Pull request by rabernat**
Supersedes #296

### CODE REVIEW

**Comment by rabernat** [comment]
Github actions is apparently broken today.

**Comment by rabernat** [comment]
Hmm, from the tests, it looks like this is breaking geoviews and jax.

**Comment by gmaze** [comment]
😿 
I have no idea why [argopy requirements](https://github.com/euroargodev/argopy/blob/master/requirements.txt) would lead to geoviews not being imported:

```
xarray>=0.15.1
scipy>=1.1.0
scikit-learn<2.0
netCDF4<1.5.9
dask>=2.9
toolz>=0.8.2
erddapy>=0.6
fsspec>=0.7.4
gsw<=3.4.0
aiohttp>=3.6.2
packaging>= 20.4
```

**Comment by rabernat** [comment]
@scottyhq any idea what is going in here?

**Comment by rabernat** [comment]
/condalock

Just rolling the dice again.

**Comment by rabernat** [comment]
Ok well now it looks like the entire test framework is broken. Check out this error from the [pangeo-notebook test](https://github.com/pangeo-data/pangeo-docker-images/runs/5850312323?check_suite_focus=true)

```
________________________ test_default_conda_environment ________________________

    def test_default_conda_environment():
>       assert sys.prefix == '/srv/conda/envs/notebook'
E       AssertionError: assert '/srv/conda' == '/srv/conda/envs/notebook'
E         - /srv/conda/envs/notebook
E         + /srv/conda
```

This can't have anything to do with argopy...something much deeper is going on.

**Comment by scottyhq** [comment]
Further up the log, you can see that there is an issue installing `rise` and the environment creation fails (no packages listed in default environment). Ideally that github action step would return a non-zero exit code. 

```
2022-04-06T12:02:05.4780815Z CONDA_PREFIX: /srv/conda/envs/notebook
2022-04-06T12:02:05.4781072Z Status: enabled
2022-04-06T12:02:05.4781200Z 
2022-04-06T12:02:05.4781206Z 
2022-04-06T12:02:05.4781434Z Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
2022-04-06T12:02:05.4782104Z Enabling notebook extension jupyter-js-widgets/extension...
2022-04-06T12:02:05.4782456Z       - Validating: [32mOK[0m
2022-04-06T12:02:05.4782597Z 
2022-04-06T12:02:05.4782666Z done
2022-04-06T12:02:05.4798457Z Rolling back transaction: ...working... [91mERROR conda.core.link:_execute(730): An error occurred while installing package 'conda-forge::rise-5.7.1-py39hf3d152e_1'.
2022-04-06T12:02:26.0640611Z [0mdone
2022-04-06T12:02:26.1498114Z [91m
2022-04-06T12:02:26.1499112Z LinkError: post-link script failed for package conda-forge::rise-5.7.1-py39hf3d152e_1
2022-04-06T12:02:26.1499886Z location of failed script: /srv/conda/envs/notebook/bin/.rise-post-link.sh
2022-04-06T12:02:26.1500317Z ==> script messages <==
2022-04-06T12:02:26.1500626Z <None>
2022-04-06T12:02:26.1500930Z ==> script output <==
2022-04-06T12:02:26.1501241Z stdout: 
2022-04-06T12:02:26.1501679Z stderr: Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
2022-04-06T12:02:26.1502496Z Traceback (most recent call last):
2022-04-06T12:02:26.1503179Z   File "/srv/conda/envs/notebook/bin/jupyter-nbextension", line 10, in <module>
2022-04-06T12:02:26.1503575Z     sys.exit(main())
2022-04-06T12:02:26.1504223Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
2022-04-06T12:02:26.1504775Z     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
2022-04-06T12:02:26.1505483Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
2022-04-06T12:02:26.1505948Z     app.start()
2022-04-06T12:02:26.1506542Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/notebook/nbextensions.py", line 980, in start
2022-04-06T12:02:26.1506985Z     super().start()
2022-04-06T12:02:26.1507569Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/jupyter_core/application.py", line 253, in start
2022-04-06T12:02:26.1508042Z     self.subapp.start()
2022-04-06T12:02:26.1508649Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/notebook/nbextensions.py", line 888, in start
2022-04-06T12:02:26.1509161Z     self.toggle_nbextension_python(self.extra_args[0])
2022-04-06T12:02:26.1509947Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/notebook/nbextensions.py", line 861, in toggle_nbextension_python
2022-04-06T12:02:26.1510370Z     return toggle(module,
2022-04-06T12:02:26.1510943Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/notebook/nbextensions.py", line 474, in enable_nbextension_python
2022-04-06T12:02:26.1511431Z     return _set_nbextension_state_python(True, module, user, sys_prefix,
2022-04-06T12:02:26.1512068Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/notebook/nbextensions.py", line 372, in _set_nbextension_state_python
2022-04-06T12:02:26.1512525Z     m, nbexts = _get_nbextension_metadata(module)
2022-04-06T12:02:26.1513111Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/notebook/nbextensions.py", line 1114, in _get_nbextension_metadata
2022-04-06T12:02:26.1513526Z     m = import_item(module)
2022-04-06T12:02:26.1514064Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/traitlets/utils/importstring.py", line 38, in import_item
2022-04-06T12:02:26.1514481Z     return __import__(parts[0])
2022-04-06T12:02:26.1514994Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/rise/__init__.py", line 3, in <module>
2022-04-06T12:02:26.1515422Z     __version__ = pkg_resources.require("rise")[0].version
2022-04-06T12:02:26.1515987Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pkg_resources/__init__.py", line 891, in require
2022-04-06T12:02:26.1516436Z     needed = self.resolve(parse_requirements(requirements))
2022-04-06T12:02:26.1517005Z   File "/srv/conda/envs/notebook/lib/python3.9/site-packages/pkg_resources/__init__.py", line 782, in resolve
2022-04-06T12:02:26.1517458Z     raise VersionConflict(dist, req).with_context(dependent_req)
2022-04-06T12:02:26.1518247Z pkg_resources.ContextualVersionConflict: (python-dateutil 2.7.5 (/srv/conda/envs/notebook/lib/python3.9/site-packages), Requirement.parse('python-dateutil>=2.8.2'), {'jupyter-client'})
2022-04-06T12:02:26.1518681Z 
2022-04-06T12:02:26.1518832Z return code: 1
2022-04-06T12:02:26.1519022Z 
2022-04-06T12:02:26.1519159Z ()
2022-04-06T12:02:26.1519338Z 
2022-04-06T12:04:04.1494982Z [0mRemoving intermediate container 5d47862b081c
2022-04-06T12:04:04.2511266Z  ---> Running in bbee2ad71544
2022-04-06T12:04:04.5591020Z Checking for pip 'requirements.txt'...
2022-04-06T12:04:12.5153573Z Removing intermediate container bbee2ad71544
2022-04-06T12:04:12.5353321Z  ---> Running in c20df38c88ca
2022-04-06T12:04:12.7688412Z Checking for 'postBuild'...
2022-04-06T12:04:20.4314562Z Removing intermediate container c20df38c88ca
2022-04-06T12:04:20.4512804Z  ---> Running in c8aa752ba10f
2022-04-06T12:04:20.7044755Z Checking for 'start'...
2022-04-06T12:04:28.3377327Z Removing intermediate container c8aa752ba10f
2022-04-06T12:04:28.3377868Z  ---> 2b949faedd57
2022-04-06T12:04:28.3454253Z Successfully built 2b949faedd57
2022-04-06T12:04:28.3499678Z Successfully tagged pangeo/pangeo-notebook:PR
2022-04-06T12:04:28.3649658Z ##[group]Run docker images
2022-04-06T12:04:28.3649924Z [36;1mdocker images[0m
2022-04-06T12:04:28.3650220Z [36;1mdocker run ${DOCKER_ORG}/pangeo-notebook:PR conda list --export[0m
2022-04-06T12:04:28.3733974Z shell: /usr/bin/bash -e {0}
2022-04-06T12:04:28.3734184Z env:
2022-04-06T12:04:28.3734386Z   DOCKER_ORG: pangeo
2022-04-06T12:04:28.3734654Z   GITHUB_SHA: 06691ceffbc92a2f1a0c468943946dd1accc23d8
2022-04-06T12:04:28.3734916Z   GITHUB_REF: refs/pull/299/merge
2022-04-06T12:04:28.3735141Z ##[endgroup]
2022-04-06T12:04:28.4426207Z REPOSITORY               TAG         IMAGE ID       CREATED         SIZE
2022-04-06T12:04:28.4426915Z pangeo/pangeo-notebook   PR          2b949faedd57   1 second ago    5.7GB
2022-04-06T12:04:28.4427364Z pangeo/base-image        PR          8ad6606b90d3   8 minutes ago   315MB
2022-04-06T12:04:28.4427790Z buildpack-deps           stretch     de7321966554   7 days ago      835MB
2022-04-06T12:04:28.4429782Z buildpack-deps           buster      cbdff219ec50   7 days ago      804MB
2022-04-06T12:04:28.4431321Z buildpack-deps           bullseye    c93648763550   7 days ago      834MB
2022-04-06T12:04:28.4455077Z node                     12-alpine   314ec282a089   7 days ago      91MB
2022-04-06T12:04:28.4455822Z node                     14-alpine   a310e5ff0582   7 days ago      119MB
2022-04-06T12:04:28.4499230Z node                     16-alpine   5521a6fdce5c   7 days ago      111MB
2022-04-06T12:04:28.4499549Z debian                   9           cb32206528ee   8 days ago      101MB
2022-04-06T12:04:28.4499827Z debian                   10          76e02db62235   8 days ago      114MB
2022-04-06T12:04:28.4500116Z debian                   11          d69c6cd3a20d   8 days ago      124MB
2022-04-06T12:04:28.4500430Z alpine                   3.12        d7db87feda9d   8 days ago      5.58MB
2022-04-06T12:04:28.4500720Z alpine                   3.13        6851ddaa64a3   8 days ago      5.61MB
2022-04-06T12:04:28.4501015Z alpine                   3.14        84b07dd2d1fd   8 days ago      5.59MB
2022-04-06T12:04:28.4501308Z node                     12          5b6c488f14dd   2 weeks ago     918MB
2022-04-06T12:04:28.4501588Z node                     14          903c2c873ea4   2 weeks ago     945MB
2022-04-06T12:04:28.4501861Z node                     16          054bccad10b0   2 weeks ago     906MB
2022-04-06T12:04:28.4502144Z ubuntu                   20.04       ff0fea8310f3   2 weeks ago     72.8MB
2022-04-06T12:04:28.4502438Z ubuntu                   18.04       b67d6ac264e4   2 weeks ago     63.2MB
2022-04-06T12:04:28.4502717Z moby/buildkit            latest      ab57028900a2   3 weeks ago     142MB
2022-04-06T12:04:28.4503006Z ubuntu                   16.04       b6f507652425   7 months ago    135MB
2022-04-06T12:04:29.3477461Z # This file may be used to create an environment using:
2022-04-06T12:04:29.3478144Z # $ conda create --name <env> --file <this file>
2022-04-06T12:04:29.3478502Z # platform: linux-64
```

**Pull request closed without merging**
