### PR TITLE
Upgrade to pangeo-forge-recipes==0.9.4

### PR DESCRIPTION
**Pull request by cisaacstern**
@scottyhq another bump to the `pangeo-forge-recipes` version. Apologies for the quick succession of PRs. Turns out there was a bug in the release added by #420, so made a quick follow-on release of `0.9.4`.

### CODE REVIEW

**Review by scottyhq — APPROVED** [review]
@cisaacstern i added you as a maintainer so you should be able to merge?

**Comment by cisaacstern** [comment]
Yes, looks like it! Thanks so much @scottyhq.

I noticed on #420 that you [manually conda-locked](https://github.com/pangeo-data/pangeo-docker-images/pull/420#issuecomment-1370383435) the PR.

For my future reference, when is this necessary? (Guessing not here, because all tests are passing.)

**Comment by scottyhq** [comment]
The CI is not well setup for simultaneous PRs (if one is merged while another is open there tend to be merge conflicts in the lockfiles, so you have to rebase/merge and relock)

**Comment by cisaacstern** [comment]
Gotcha! Makes sense.

**Pull request merged**
