### PR TITLE
GPU-enabled tensorflow from conda-forge (pangeo-ml image) + pangeo-notebook updates

### PR DESCRIPTION
**Pull request by scottyhq**
- also remove sat-stac and sat-search in favor of pystac and pystac-client
- fsspec-reference-maker -> kerchunk

### CODE REVIEW

**Comment by scottyhq** [comment]
@rabernat @jhamman with the recent changes to the ML image using a compound specification on top of pangeo notebook, condalock is having a terrible time solving the environment. It seems to either [fail](https://github.com/pangeo-data/pangeo-docker-images/runs/4086518465?check_suite_focus=true) or take [hours to figure out a solution](https://github.com/pangeo-data/pangeo-docker-images/actions/runs/1414762866). I suspect this is due both to lots of complicated dependency solving and mixing channels (https://github.com/conda/conda/issues/9993)

In the interest of continuing to update pangeo-notebook *I'd like to switch to only using the conda-forge channel* (and thus tensorflow on CPU for a bit, you can point to older images that do have GPU support, but I haven't heard anyone confirm they even work for quite a while since https://medium.com/pangeo/deep-learning-with-gpus-on-pangeo-9466e25bfd74). Good news is that tensorflow builds for GPUs seem imminent https://github.com/conda-forge/tensorflow-feedstock/pull/157

**Comment by wolfv** [comment]
I am uploading the GPU builds as we speak :)

**Comment by rabernat** [comment]
> I am uploading the GPU builds as we speak :)

This is a really fantastic development. Thanks @wolfv for your work on conda forge (and mamba)!

**Pull request merged**
