### PR TITLE
Adding cfgrib to notebook env

### PR DESCRIPTION
**Pull request by rsignell-usgs**
/condalock
Adding cfgrib allows us to run the [xarray GRIB example notebook](http://xarray.pydata.org/en/stable/examples/ERA5-GRIB-example.html)

### CODE REVIEW

**Comment by scottyhq** [comment]
thanks @rsignell-usgs - i'm going to try to tackle https://github.com/pangeo-data/pangeo-docker-images/issues/92 and then ask you to resubmit this.

**Comment by rsignell-usgs** [comment]
@scottyhq okay now to add?

**Comment by scottyhq** [comment]
closed by #117

**Pull request closed without merging**
