### PR TITLE
bump to python 310 in all images

### LINKED ISSUE #216: Installing aws cli version 2 and/or its dependency for the `help` subcommand
Using an image built `FROM pangeo/pangeo-notebook:2021.05.15` I'm using the `aws` CLI.

1. I wonder if you think we should install version 2 of the CLI (curl, unzip, :scream:, move on filesystem, done, :nauseated_face:).
2. I also wonder if you think we should install `groff` (an apt package). Apparently it is a dependency to run `help` sub-commands of like `aws s3 help` but `groff` isn't available by default in the `pangeo-notebook` image.

### Example output with `aws` CLI v1 trying to use `help` sub-command

```
$ aws
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: command



$ aws help

Could not find executable named "groff"
```

### LINKED ISSUE #332: Bump to Python 3.10
It's been out for a while and 3.11 is on the horizon. I suspect most packages are now available on conda-forge 
https://peps.python.org/pep-0602/

### PR DESCRIPTION
**Pull request by scottyhq**
closes #332

### CODE REVIEW

**Comment by scottyhq** [comment]
currently blocked by python 3.10 support in apache-beam https://github.com/apache/beam

**Comment by rabernat** [comment]
xref https://github.com/apache/beam/issues/21585

**Comment by consideRatio** [comment]
Tracked by https://github.com/apache/beam/pull/23587 I think.

**Comment by scottyhq** [comment]
I'm going to go ahead and merge this since tests are passing. 

So note that 

| tag | python version | 
| - | - | 
| 2022.11.16 | python 3.9 |
| >=2022.12.01 | python 3.10 |

**Pull request merged**
